const data = {
    products: [
        {
            _id: '1',
            name:'Nike Slim Shirts',
            category: 'Cotton Shirts',
            image: 'jj.jpg',
            price:120,
            brand:'Nike',
            rating:3.5,
            numreviews:18,
            description:'high quality Product',
        },
        {
            _id: '2',
            name:'Regular Fit Shirts',
            category: 'Casual Shirts',
            image: 'shirt1.jpeg',
            price:110,
            brand:'Nike',
            rating:3,
            numreviews:17,
            description:'high quality Product',
        },
        {
            _id: '3',
            name:'Lymio Casual Shirts',
            category: 'Casual Shirts',
            image: 'pp.webp',
            price:130,
            brand:'Lymio',
            rating:5,
            numreviews:16,
            description:'high quality Product',
        },
        {
            _id: '4',
            name:'Korean Slim Shirts',
            category: ' Cotton Shirts',
            image: 'll.jpg',
            price:115,
            brand:'KSlim',
            rating:3.5,
            numreviews:15,
            description:'high quality Product',
        },
        {
            _id: '5',
            name:'Lacoste Free Shirts',
            category: 'Cotton Shirts',
            image: 'cc.jpg',
            price:125,
            brand:'Lacoste',
            rating:3,
            numreviews:10,
            description:'high quality Product',
        },
        {
            _id: '6',
            name:'Adidas Fit Shirts',
            category: 'Casual Shirts',
            image: 'kk.webp',
            price:140,
            brand:'Adidas',
            rating:4.5,
            numreviews:12,
            description:'high quality Product',
        },
    ]
};
export default data;